# Generated by Django 5.1.4 on 2026-06-10 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="If null, user has access to all branches",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="warehouses.branch",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.role"
            ),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="tenantmembership",
            unique_together={("user", "tenant")},
        ),
    ]
