# Generated by Django 5.1.4 on 2026-06-10 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "subdomain",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Store"),
                            ("supermarket", "Supermarket"),
                            ("pharmacy", "Pharmacy"),
                            ("restaurant", "Restaurant"),
                            ("hotel", "Hotel"),
                            ("warehouse", "Warehouse"),
                            ("manufacturing", "Manufacturing"),
                            ("fashion", "Fashion"),
                            ("construction", "Construction"),
                            ("distributor", "Distributor"),
                            ("electronics", "Electronics"),
                            ("agriculture", "Agriculture"),
                            ("service", "Service Business"),
                            ("wholesale", "Wholesale"),
                            ("other", "Other"),
                        ],
                        default="retail",
                        max_length=30,
                    ),
                ),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("plan_started_at", models.DateTimeField(blank=True, null=True)),
                ("plan_expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_trial", models.BooleanField(default=True)),
                ("max_users", models.PositiveIntegerField(default=3)),
                ("max_products", models.PositiveIntegerField(default=500)),
                ("max_warehouses", models.PositiveIntegerField(default=1)),
                ("max_monthly_orders", models.PositiveIntegerField(default=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="tenant_logos/%Y/"
                    ),
                ),
                ("primary_color", models.CharField(default="#6366F1", max_length=7)),
                ("secondary_color", models.CharField(default="#8B5CF6", max_length=7)),
                ("currency", models.CharField(default="NGN", max_length=10)),
                ("currency_symbol", models.CharField(default="₦", max_length=5)),
                ("timezone", models.CharField(default="Africa/Lagos", max_length=50)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=100)),
                (
                    "default_tax_rate",
                    models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
                ),
                ("feature_pos", models.BooleanField(default=True)),
                ("feature_manufacturing", models.BooleanField(default=False)),
                ("feature_ecommerce", models.BooleanField(default=False)),
                ("feature_multi_currency", models.BooleanField(default=False)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("onboarding_step", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("invoice_prefix", models.CharField(default="INV", max_length=20)),
                ("order_prefix", models.CharField(default="ORD", max_length=20)),
                ("po_prefix", models.CharField(default="PO", max_length=20)),
                ("low_stock_alert_email", models.BooleanField(default=True)),
                ("daily_report_email", models.BooleanField(default=False)),
                ("require_purchase_approval", models.BooleanField(default=False)),
                ("require_sales_approval", models.BooleanField(default=False)),
                ("allow_negative_stock", models.BooleanField(default=False)),
                (
                    "stock_valuation_method",
                    models.CharField(
                        choices=[
                            ("fifo", "FIFO"),
                            ("lifo", "LIFO"),
                            ("avg", "Weighted Average"),
                        ],
                        default="avg",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_settings",
            },
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_slug_3181c2_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["subdomain"], name="tenants_subdoma_69cf01_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["plan", "is_active"], name="tenants_plan_09dc53_idx"
            ),
        ),
    ]
