# Generated by Django 5.1.4 on 2026-06-10 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("tenants", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "transfer_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_transit", "In Transit"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("shipped_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="warehouses.warehouse",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transfers",
            },
        ),
        migrations.CreateModel(
            name="StockTransferItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "quantity_requested",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "quantity_received",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stocktransfer",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "stock_transfer_items",
            },
        ),
        migrations.CreateModel(
            name="BatchLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("batch_number", models.CharField(db_index=True, max_length=100)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("supplier_reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "batch_lots",
                "indexes": [
                    models.Index(
                        fields=["tenant", "product", "expiry_date"],
                        name="batch_lots_tenant__9589cd_idx",
                    )
                ],
                "unique_together": {("tenant", "product", "warehouse", "batch_number")},
            },
        ),
        migrations.CreateModel(
            name="SerialNumber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("serial_number", models.CharField(db_index=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("sold", "Sold"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("reserved", "Reserved"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("sold_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_numbers",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_numbers",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "serial_numbers",
                "indexes": [
                    models.Index(
                        fields=["tenant", "product", "status"],
                        name="serial_numb_tenant__3ab365_idx",
                    )
                ],
                "unique_together": {("tenant", "product", "serial_number")},
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Stock committed to undelivered orders",
                        max_digits=15,
                    ),
                ),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="products.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_levels",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock_levels",
                "indexes": [
                    models.Index(
                        fields=["tenant", "product", "warehouse"],
                        name="stock_level_tenant__de891a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "warehouse"],
                        name="stock_level_tenant__eccc13_idx",
                    ),
                ],
                "unique_together": {("tenant", "product", "variant", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("opening", "Opening Stock"),
                            ("purchase", "Purchase Receipt"),
                            ("sale", "Sale"),
                            ("transfer_out", "Transfer Out"),
                            ("transfer_in", "Transfer In"),
                            ("adjustment_in", "Adjustment (Increase)"),
                            ("adjustment_out", "Adjustment (Decrease)"),
                            ("return_customer", "Return from Customer"),
                            ("return_supplier", "Return to Supplier"),
                            ("damage", "Damage / Write-off"),
                            ("production_input", "Production Input (Consumed)"),
                            ("production_output", "Production Output (Finished)"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "quantity_before",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "quantity_after",
                    models.DecimalField(decimal_places=3, max_digits=15),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. sale_order, purchase_order, stock_transfer",
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "batch_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="products.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="products.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="warehouses.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "product", "-created_at"],
                        name="stock_movem_tenant__5d6fd9_idx",
                    ),
                    models.Index(
                        fields=["tenant", "movement_type", "-created_at"],
                        name="stock_movem_tenant__cafcb3_idx",
                    ),
                    models.Index(
                        fields=["tenant", "warehouse", "-created_at"],
                        name="stock_movem_tenant__eb6c38_idx",
                    ),
                    models.Index(
                        fields=["tenant", "reference_id"],
                        name="stock_movem_tenant__2be38f_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["tenant", "status", "-created_at"],
                name="stock_trans_tenant__1e6fb1_idx",
            ),
        ),
    ]
