# Generated by Django 5.1.4 on 2026-06-10 00:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("low_stock_digest", "Low Stock Digest"),
                            ("batch_expiry", "Batch Expiry"),
                            ("order_created", "Order Created"),
                            ("order_confirmed", "Order Confirmed"),
                            ("payment_received", "Payment Received"),
                            ("po_approved", "PO Approved"),
                            ("expense_approved", "Expense Approved"),
                            ("user_invited", "User Invited"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = broadcast to all tenant admins",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "recipient", "is_read", "-created_at"],
                        name="notificatio_tenant__57536c_idx",
                    )
                ],
            },
        ),
    ]
